steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cobalt-tools", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cobalt-tools"]
images:
  - "gcr.io/$PROJECT_ID/cobalt-tools"
